<?php
/**
 * ONIKA — default configuration.
 *
 * Do NOT edit this file to change settings on a live site: create
 * `config.local.php` next to it that returns an array with only the keys
 * you want to override, e.g.
 *
 *     <?php return ['debug' => true, 'timezone' => 'Europe/Warsaw'];
 */
return [
    // Show detailed error messages (turn on only while developing).
    'debug' => false,

    // Time zone used for dates in the admin panel and on order pages.
    'timezone' => 'Europe/Kyiv',

    // Default admin account created on first run. The password must be
    // changed at first login (the panel will not open until it is).
    'admin_default_user' => 'admin',
    'admin_default_pass' => 'onika2024',

    // Session settings.
    'session_name'       => 'onika_sid',
    'customer_session_days' => 30,
    'admin_idle_minutes'    => 480,

    // Uploads.
    'upload_max_bytes' => 8 * 1024 * 1024,
    'upload_max_files' => 12,
    'upload_max_side'  => 2000,

    // Number of products per page in the storefront / admin.
    'per_page'       => 24,
    'admin_per_page' => 30,

    // Number of database backups to keep.
    'backups_keep' => 20,
];
